### ISSUE TITLE
Add the trace id to metering events

### ISSUE THREAD

**Issue by fschoell** [dfuse-io/dmetering#3]
This would be helpful to generate stats based on connections. For example the count of distinct trace ids grouped by endpoint.

**Comment by jubeless** [comment]
Metering events, are aggregated to reduce the data impact on the system, as such adding a trace ID (which would be unique per request) would break that. 

Moreover, the goal of metrics are not to get a per request (or connection) perspective of the stack but rather track consumption of the resources. 

To get request & connection based stats, we have a setup a Log Router in GCP, which sinks specific Substreams logs to BigQuery. This Substreams log contains all the relevant information for a given Substreams connection. The Log filter is

```
resource.type="k8s_container"
jsonPayload.message="substreams request stats"
severity=INFO
resource.labels.container_name="substreams"
```
